#!/bin/bash -e
#
# GNU Bash required for process substitution `<()` later.
#
# Environment variables:
#

# Install xray and configure socks inbound
cd "$GITHUB_WORKSPACE"
sudo bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --beta
sudo apt-get install -y autossh sshpass
echo '{
  "inbounds": [
    {
      "id": 5,
      "userId": 0,
      "enable": true,
      "expiryTime": 0,
      "trafficReset": "never",
      "lastTrafficResetTime": 0,
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "comment": "",
            "enable": true,
            "expiryTime": 0,
            "flow": "xtls-rprx-vision",
            "id": "97f3c32a-df7f-4ee6-b8f7-17a4f4a5163b",
            "limitIp": 0,
            "reset": 0,
            "subId": "cdc3kadx35r2o6pv",
            "tgId": 0
          }
        ],
        "decryption": "none",
        "encryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "externalProxy": [],
        "realitySettings": {
          "show": false,
          "xver": 0,
          "target": "entekhab.ir:443",
          "serverNames": ["entekhab.ir"],
          "privateKey": "sJXvSA5qKbDhGzoXqrYp_ePQUWWv5BnxHouQpaIBo0Q",
          "minClientVer": "",
          "maxClientVer": "",
          "maxTimediff": 0,
          "shortIds": [
            "90",
            "40dee2",
            "bda0",
            "728f08b3cabe",
            "706e9fbfa56a5cda",
            "ea2563fe",
            "e1db41c0a4",
            "3924e9bd0581f5"
          ],
          "mldsa65Seed": "",
          "settings": {
            "publicKey": "6D2blS4UM4zEP8xK_eMUUuOewIouxEZKuCwE4KJR6RM",
            "fingerprint": "chrome",
            "serverName": "",
            "spiderX": "/",
            "mldsa65Verify": ""
          }
        },
        "tcpSettings": {
          "acceptProxyProtocol": false,
          "header": {
            "type": "none"
          }
        }
      },
      "sniffing": {
        "enabled": false,
        "destOverride": ["http", "tls", "quic", "fakedns"],
        "metadataOnly": false,
        "routeOnly": false
      },
      "nodeId": null
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}' | sudo tee /usr/local/etc/xray/config.json >/dev/null
sudo systemctl restart xray

# cloudflare tunnel

#./cloudflared tunnel --no-autoupdate --url tcp://localhost:9999 2>&1 | tee cloudflared-socks.log | sed -u 's/^/cloudflared: /' &
# autossh -oStrictHostKeyChecking=no -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -R 8778:localhost:4433 serveo.net &

mkdir ~/.ssh

ssh-keyscan "$SERVER_IP" >> ~/.ssh/known_hosts

sshpass -p "$SERVER_PASS" ssh -N \
  -o "ServerAliveInterval 30" \
  -o "ServerAliveCountMax 3" \
  -o "TCPKeepAlive yes" \
  -R 0.0.0.0:443:127.0.0.1:443 \
  "${SERVER_USER}@${SERVER_IP}" &

# url=$(head -1 <(tail -f cloudflared-socks.log | grep --line-buffered -o 'https://.*\.trycloudflare.com'))
#hostname=${url:8}
#message='sudo sh -c '"'"'echo -e $(resolveip -s '"$hostname"')"\t'"$hostname"'" >> /etc/hosts'"'"' && sudo -u tor cloudflared access tcp --hostname '"$url"' --url 0.0.0.0:9999 & sudo -u tor xray -c /config.json & sudo ./v2ray-transparent.bash -s'

#ruinerme "$message"


sleep 999999
