#!/bin/bash -e

cd "$GITHUB_WORKSPACE"

cloudflared_url=https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
curl --location --silent --output cloudflared "$cloudflared_url"
chmod +x cloudflared
