# Thanks: https://github.com/valeriangalliat/action-sshd-cloudflared
name: CI
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "20 1,7,13,19 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
      TG_SESSION_STRING: ${{ secrets.TG_SESSION_STRING }}
      TG_TARGET_ID: ${{ secrets.TG_TARGET_ID }}
      TG_API_ID: ${{ secrets.TG_API_ID }}
      TG_API_HASH: ${{ secrets.TG_API_HASH }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      SECRET_FILES: ${{ secrets.SECRET_FILES }}
    steps:
      - run: sudo rm -rf /usr/local /opt/hostedtoolcache /opt/az /opt/microsoft /opt/pipx /opt/google
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - uses: actions/checkout@v3
      - run: if [ ! -z "$SECRET_FILES" ]; then echo $SECRET_FILES | base64 --decode | tar -xz -C ./home/; fi
      - run: cp -r ./home/. ~
      - run: curl -L 'https://github.com/glotlabs/gdrive/releases/download/3.6.0/gdrive_linux-x64.tar.gz' | tar -xz -C ~/.local/bin
      - run: sudo apt-get install -y unrar p7zip megatools aria2
      - run: pip install -r requirements.txt
      - run: pip install --upgrade python-telegram
      - run: $GITHUB_WORKSPACE/setup-cloudflared
        shell: bash
      # - run: $GITHUB_WORKSPACE/setup-proxies
      #   shell: bash
      - run: $GITHUB_WORKSPACE/setup-ssh
        shell: bash
      - name: Keep Alive
        run: |
          tmux wait-for channel
          echo 'Session ended'
          pkill cloudflared
          pkill sshd
